/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum SassSyntax {
  Sass = 'Sass',
  Css = 'Css',
  Scss = 'Scss'
}
export const enum SassOutputStyle {
  Expanded = 'Expanded',
  Compressed = 'Compressed'
}
export interface SassOptions {
  data?: string
  file?: string
  saasSyntax?: SassSyntax
  outputStyle?: SassOutputStyle
  includePaths?: Array<string>
}
export function compileSass(input: string): string
export function compileSassFromFile(filePath: string): string
export function compileSassFromOptions(options: SassOptions): string
