name: Build x86_64-pc-windows-msvc

env:
  DEBUG: napi:*
  APP_NAME: gulp-grass-sass
  
on:
  workflow_dispatch:

jobs:
  build:
    name: build-x86_64-pc-windows-msvc
    env: 
      TARGET: x86_64-pc-windows-msvc
    runs-on: windows-latest
    steps:   
      - uses: actions/checkout@v4.1.7
      
      - name: Install Node.JS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{ env.TARGET }}
                  
      - uses: bahmutov/npm-install@v1.6.0
      
      - name: Build binaries
        run: npm run build --target ${{ env.TARGET }}

      - name: Show current location and list packages
        run: |
          echo "Current Location: $(pwd)"
          ls -L .
        shell: bash

      - name: Move Binaries
        run: |
          [[ -d "${{ github.workspace }}/${{ env.TARGET }}" ]] && mv "${{ github.workspace }}/${{ env.TARGET }}/*.node" "${{ github.workspace }}/" 2>/dev/null       
        shell: bash
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: bindings-${{ env.TARGET }}
          path: ${{ github.workspace }}/*.node
          if-no-files-found: error
          
  test:
    name: test-x86_64-pc-windows-msvc
    needs:
      - build
    env: 
      TARGET: x86_64-pc-windows-msvc
    strategy:
      matrix:
        node: ['18','20']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7    
      
      - name: Install Node.JS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
          
      - uses: bahmutov/npm-install@v1.6.0
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: bindings-${{ env.TARGET }}
          path: .
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Test bindings
        run: npm run test
    
