name: Build x86_64-unknown-linux-gnu

env:
  DEBUG: napi:*
  APP_NAME: gulp-grass-sass
  
on:
  workflow_dispatch:

jobs:
  build:
    name: build-x86_64-unknown-linux-gnu
    env: 
      TARGET: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v4.1.7
      
      - name: Install Node.JS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.TARGET }}
                  
      - uses: bahmutov/npm-install@v1.6.0
      
      - name: Build binaries
        run: npm run build -- --target ${{ env.TARGET }}

      - name: Show current location and list packages
        run: |
          echo "Current Location: $(pwd)"
          ls -L .
        shell: bash

      - name: Move Binaries
        run: |
          [[ -d "${{ github.workspace }}/${{ env.TARGET }}" ]] && mv "${{ github.workspace }}/${{ env.TARGET }}/*.node" "${{ github.workspace }}/" 2>/dev/null       
        shell: bash
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: bindings-${{ env.TARGET }}
          path: ${{ github.workspace }}/**/*.node
          if-no-files-found: error
